# 데이터 팩 생성기

import os
import json
from packaging import version as ver

# 경로
def create_folder(version, format_version, base_dir):
   folder_name = f"default_{version}"
   folder_path = os.path.join(base_dir, folder_name)
   
   data_path = os.path.join(folder_path, "data")
   default_inside_data = os.path.join(data_path, "default")

   os.makedirs(default_inside_data, exist_ok=True)

   pack_mcmeta_path = os.path.join(folder_path, "pack.mcmeta")
   pack_mcmeta_content = {
      "pack": {
         "description": "generated by gen.py",
         "pack_format": format_version
      }
   }

   with open(pack_mcmeta_path, "w", encoding="utf-8") as f:
      json.dump(pack_mcmeta_content, f, ensure_ascii=False, indent=2)
   print(f"{folder_name} 데이터 팩과 pack.mcmeta가 생성되었습니다.")

# 입력
version = input("마인크래프트 버전 입력: ")

base_dir = os.path.dirname(os.path.abspath(__file__))
json_path = os.path.join(base_dir, "format.json")

# json 불러오기
with open(json_path, "r", encoding="utf-8") as f:
   ranges = json.load(f)

# 버전 그룹
group = None
format_version = None

for value, val in ranges.items():
   # 다중 버전
   if "-" in value:
      first, second = value.split("-")

      start = ver.parse(first)
      end = ver.parse(second)
   # 단일 버전
   else:
      start = end = ver.parse(value)

   if start <= ver.parse(version) <= end:
      group = value
      format_version = val
      break

# 생성
create_folder(group, format_version, base_dir)